DROP TABLE IF EXISTS TBL_PRODUCTS;
 
CREATE TABLE TBL_PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_name VARCHAR(250) NOT NULL,
  short_description VARCHAR(250) NOT NULL,
  price VARCHAR(250) DEFAULT NULL
);